version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abghse
      MYSQL_DATABASE: sales_system
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+mysqlconnector://root:abghse@db/sales_system
    ports:
      - "8000:8000"

volumes:
  db_data: